# Define a Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  # Metadata for the deployment
spec:
  replicas: 3
  # Selector to match pods
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      # Labels for the pod template
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          # Use the Docker image from DockerHub
          image: serdardevops/myapp:latest
          ports:
            - containerPort: 8080
              # Port the container listens on